tutorial_app/models.py
"""Database models for SQLAlchemy."""
from flask_login import UserMixin
from tutorial_app import db

from tutorial_app.utils import FormEnum


class TutorialCategory(FormEnum):
    """Categories of grocery items."""

    ML = "Machine Learning"
    STATS = "Statistics"
    DL = "Deep Learning"
    RL = "Reinforcement Learning"
    OTHER = "Other"


class Difficulty(FormEnum):
    """Categories of grocery items."""

    BEGINNER = "Beginner"
    INTERMEDIATE = "Intermediate"
    EXPERT = "Expert"


class User(UserMixin, db.Model):
    """User model."""

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), nullable=False)
    password = db.Column(db.String(160), nullable=False)
    saved_tutorials = db.relationship(
        "Tutorial", secondary="saved_tutorials", back_populates="saved_by"
    )


class Tutorial(db.Model):
    """Tutorial model."""

    id = db.Column(db.Integer, primary_key=True)
    category = db.Column(
        db.Enum(TutorialCategory), default=TutorialCategory.OTHER
    )
    title = db.Column(db.String(40), nullable=False)
    difficulty = db.Column(
        db.Enum(Difficulty), default=Difficulty.INTERMEDIATE
    )
    body = db.Column(db.String(10000), nullable=False)
    saved_by = db.relationship(
        "User",
        secondary="saved_tutorials",
        back_populates="saved_tutorials",
    )


class Resource(db.Model):
    """Resource model."""

    id = db.Column(db.Integer, primary_key=True)
    category = db.Column(
        db.Enum(TutorialCategory), default=TutorialCategory.OTHER
    )
    title = db.Column(db.String(40), nullable=False)
    description = db.Column(db.String(120), nullable=True)
    link = db.Column(db.String(120), nullable=False)


saved_tutorial_table = db.Table(
    "saved_tutorials",
    db.Column("tutorial_id", db.Integer, db.ForeignKey("tutorial.id")),
    db.Column("user_id", db.Integer, db.ForeignKey("user.id")),
)

tutorial_app/main/forms.py
"""Main forms."""
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SelectField,
    SubmitField,
    FloatField,
    TextAreaField,
)
from wtforms.validators import DataRequired, Length, URL
from tutorial_app.models import (
    Tutorial,
    Resource,
    TutorialCategory,
    Difficulty,
)


class TutorialForm(FlaskForm):
    """Form for adding/updating a Tutorial."""

    category = SelectField(
        "Category",
        choices=TutorialCategory.choices(),
        validators=[DataRequired()],
    )
    title = StringField("Title", validators=[DataRequired(), Length(max=80)])
    difficulty = SelectField(
        "Difficulty",
        choices=Difficulty.choices(),
        validators=[DataRequired()],
    )
    body = TextAreaField(
        "Content", validators=[DataRequired(), Length(min=5)]
    )
    submit = SubmitField("Submit")


class ResourceForm(FlaskForm):
    """Form for adding/updating a Resource."""

    category = SelectField(
        "Category",
        choices=TutorialCategory.choices(),
        validators=[DataRequired()],
    )
    title = StringField("Title", validators=[DataRequired(), Length(max=80)])
    description = TextAreaField("Description", validators=[Length(max=350)])
    link = StringField(
        "Link", validators=[DataRequired(), URL(), Length(max=300)]
    )
    submit = SubmitField("Submit")

tutorial_app/__init__.py
from flask import Flask
from flask_bcrypt import Bcrypt
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from tutorial_app.config import Config
import os

app = Flask(__name__)
app.config.from_object(Config)
app.secret_key = os.urandom(24)


db = SQLAlchemy(app)
login_manager = LoginManager(app)
login_manager.login_view = "auth.signin"
bcrypt = Bcrypt(app)

from tutorial_app.models import User


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


from tutorial_app.auth.routes import auth as auth_routes
from tutorial_app.main.routes import main as main_routes

app.register_blueprint(main_routes)
app.register_blueprint(auth_routes)


with app.app_context():
    db.create_all()

tutorial_app/main/routes.py
"""Main routes."""
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, current_user
from tutorial_app.main.forms import TutorialForm, ResourceForm
from tutorial_app.models import Tutorial, Resource, User

from tutorial_app import db

# TODO: enable user to track their own progress?

main = Blueprint("main", __name__)


@main.route("/")
def homepage():
    """Return landing page with list of tutorials."""
    tutorials = Tutorial.query.all()
    return render_template("index.html", tutorials=tutorials)


@main.route("/new_resource", methods=["GET", "POST"])
@login_required
def new_resource():
    """Add new tutorial or resource to the site."""
    form = ResourceForm()

    if form.validate_on_submit():
        resource = Resource(
            category=form.category.data,
            title=form.title.data,
            link=form.link.data,
            description=form.description.data,
        )
        db.session.add(resource)
        db.session.commit()
        flash("Thank you for sharing your new resource!")
        return redirect(url_for("main.resources"))
    return render_template("new_resource.html", form=form)


@main.route("/new_tutorial", methods=["GET", "POST"])
@login_required
def new_tutorial():
    """Add new tutorial or resource to the site."""
    form = TutorialForm()

    if form.validate_on_submit():
        tutorial = Tutorial(
            category=form.category.data,
            title=form.title.data,
            difficulty=form.difficulty.data,
            body=form.body.data,
        )
        db.session.add(tutorial)
        db.session.commit()
        flash("Thank you for adding this tutorial!")
        return redirect(
            url_for("main.tutorial_details", tutorial_id=tutorial.id)
        )
    return render_template("new_tutorial.html", form=form)


@main.route("/resources")
def resources():
    """See list of resources."""
    # Resources won't have a details page
    # All resources have a short description and an external link
    resources = Resource.query.all()
    return render_template("resources.html", resources=resources)


@main.route("/resources/delete/<resource_id>")
@login_required
def delete_resource(resource_id):
    """Delete resource by id."""
    # We also have the poor "real world" case of anyone logged in
    # being able to delete a resource, but for our MVP that's fine
    resource = Resource.query.get(resource_id)
    db.session.delete(resource)
    db.session.commit()
    flash("Resource successfully deleted!")
    return redirect(url_for("main.resources"))


@main.route("/tutorials/<tutorial_id>")
def tutorial_details(tutorial_id):
    """View tutorial content."""
    # In the future it would be nice if users could track their progress!
    tutorial = Tutorial.query.get(tutorial_id)
    return render_template("tutorial_detail.html", tutorial=tutorial)


@main.route("/tutorials/edit/<tutorial_id>", methods=["GET", "POST"])
@login_required
def edit_tutorial(tutorial_id):
    """Edit tutorial details."""
    # Even though this isn't a perfect "real world" approach, for now anyone can
    # edit a tutorial
    tutorial = Tutorial.query.get(tutorial_id)
    form = TutorialForm(obj=tutorial)
    if form.validate_on_submit():
        tutorial.title = form.title.data
        tutorial.category = form.category.data
        tutorial.difficulty = form.difficulty.data
        tutorial.body = form.body.data
        db.session.commit()
        flash("Tutorial has been successfully updated.")
        return redirect(
            url_for("main.tutorial_details", tutorial_id=tutorial.id)
        )
    return render_template("edit_tutorial.html", form=form, tutorial=tutorial)


@main.route("/tutorials/delete/<tutorial_id>")
@login_required
def delete_tutorial(tutorial_id):
    """Delete tutorial."""
    # We also have the poor "real world" case of anyone logged in
    # being able to delete a tutorial, but for our MVP that's fine
    tutorial = Tutorial.query.get(tutorial_id)
    db.session.delete(tutorial)
    db.session.commit()
    flash("Tutorial successfully deleted!")
    return redirect(url_for("main.homepage"))

tutorial_app/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <title>Machine Learning Tutorial Central</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <link rel="stylesheet" href="/static/bootstrap.min.css">
  <link rel="stylesheet" href="/static/style.css">
</head>

<body>
  <div id="content">
    {% for message in get_flashed_messages() %}
    <p>{{ message }}</p>
    {% endfor %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="{{ url_for('main.homepage') }}"><img src="{{ url_for('static', filename='assets/logo.png') }}" alt="Brain logo for ML Central"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.resources') }}">Resources</a>
          </li>
          {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.new_tutorial') }}">New Tutorial</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.new_resource') }}">New Resource</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.signout') }}">Sign Out</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.signin') }}">Sign In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('auth.signup') }}">Sign Up</a>
            </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search Tutorials</button>
        </form>
      </div>
    </nav>
    {% block content %}{% endblock %}
  </div>
</body>

</html>

tutorial_app/templates/edit_tutorial.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-9 text-center m-auto">

  <h1 class="mt-3">Edit Tutorial</h1>
  <small>We'll review your edits and post your updates as soon as possible!</small>

  <form action="{{ url_for('main.edit_tutorial', tutorial_id=tutorial.id) }}" method="POST" class="m-auto text-center col-md-6">
    {{ form.csrf_token }}
    <fieldset>
      <legend class="mt-3">Add Your Tutorial!</legend>
      <div class="form-group col">
        <div class="col-sm-10">
          {{ form.category.label }}
          {{ form.category }}
        </div>
      </div>
      <ul>
        {% for error in form.category.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      <div class="form-group col">
        <div class="col-sm-10">
          {{ form.title.label }}
          {{ form.title }}
        </div>
      </div>
      <ul>
        {% for error in form.title.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      <div class="form-group col">
        <div class="col-sm-10">
          {{ form.difficulty.label }}
          {{ form.difficulty }}
        </div>
      </div>
      <ul>
        {% for error in form.difficulty.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      <div class="form-group">
        {{ form.body.label }}
        <!-- <textarea class="form-control" rows="3" placeholder="Your content goes here!"> -->
          {{ form.body }}
        <!-- </textarea> -->
      </div>
      <ul>
        {% for error in form.body.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      {{ form.submit }}
    </fieldset>
  </form>

</div>

{% endblock %}

tutorial_app/templates/index.html
{% extends 'base.html' %}
{% block content %}

<div class="jumbotron mb-10 text-center">
  <h1>Machine Learning Central</h1>

  <h4 class="lead">Your community for all things Machine Learning Engineering!</h4>
  <hr class="my-4">

  <p>With content for the newest of beginners through experts in their fields looking to brush up,
  <em>ML Central</em> has it all for you!</p>
</div>

<div class="m-auto text-center col-md-12">

<h2>Browse Tutorials</h2>

{% for tutorial in tutorials %}
  <div class="card text-white bg-primary mt-5 mb-3 ml-auto mr-auto" style="max-width: 80rem;">
    <div class="card-header">{{ tutorial.difficulty }}</div>
    <div class="card-body">
      <h4 class="card-title">{{ tutorial.title }}</h4>
      <p class="card-text">{{ tutorial.category }}</p>
      <a href="{{ url_for('main.tutorial_details', tutorial_id=tutorial.id) }}">Get Started!</a>
    </div>
  </div>
{% endfor %}

</div>

{% endblock %}

tutorial_app/templates/new_resource.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-9 text-center m-auto">

  <h1 class="mt-3">New Resource</h1>
  <small>Thank you for your contributions to this community!</small>

  <form action="{{ url_for('main.new_resource') }}" method="POST" class="m-auto text-center col-md-6">
    {{ form.csrf_token }}
    <fieldset>
      <legend class="mt-3">Add Your Resource!</legend>
      <div class="form-group col">
        <div class="col-sm-10">
          {{ form.category.label }}
          {{ form.category }}
        </div>
      </div>
      <ul>
        {% for error in form.category.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      <div class="form-group col">
        <div class="col-sm-10">
          {{ form.title.label }}
          {{ form.title }}
        </div>
      </div>
      <ul>
        {% for error in form.title.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      <div class="form-group col">
        <div class="col-sm-10">

          {{ form.description.label }}
          <!-- <textarea rows="3" class="form-control"> -->
          {{ form.description }}
          <!-- </textarea> -->
        </div>
      </div>
      <ul>
        {% for error in form.description.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      <div class="form-group col">
        <div class="col-sm-10">
          {{ form.link.label }}
          {{ form.link }}
        </div>
      </div>
      <ul>
        {% for error in form.link.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      {{ form.submit }}
    </fieldset>
  </form>

</div>

{% endblock %}

tutorial_app/templates/new_tutorial.html
{% extends 'base.html' %}
{% block content %}

<div class="col-md-9 text-center m-auto">

  <h1 class="mt-3">New Tutorial</h1>
  <small>New tutorials go through a short review process to ensure they meet our quality standards.</small>

  <form action="{{ url_for('main.new_tutorial') }}" method="POST" class="m-auto text-center col-md-6">
    {{ form.csrf_token }}
    <fieldset>
      <legend class="mt-3">Add Your Tutorial!</legend>
      <div class="form-group col">
        <div class="col-sm-10">
          {{ form.category.label }}
          {{ form.category }}
        </div>
      </div>
      <ul>
        {% for error in form.category.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      <div class="form-group col">
        <div class="col-sm-10">
          {{ form.title.label }}
          {{ form.title }}
        </div>
      </div>
      <ul>
        {% for error in form.title.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      <div class="form-group col">
        <div class="col-sm-10">
          {{ form.difficulty.label }}
          {{ form.difficulty }}
        </div>
      </div>
      <ul>
        {% for error in form.difficulty.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      <div class="form-group">
        {{ form.body.label }}
        <!-- <textarea class="form-control" rows="3" placeholder="Your content goes here!"> -->
          {{ form.body }}
        <!-- </textarea> -->
      </div>
      <ul>
        {% for error in form.body.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      {{ form.submit }}
    </fieldset>
  </form>

</div>

{% endblock %}

tutorial_app/templates/resources.html
{% extends 'base.html' %}
{% block content %}

<div class="m-auto text-center col-md-6">
  <h1>Browse Resources</h1>

  {% for resource in resources %}
  <div class="card text-white bg-primary mt-5 mb-3 ml-auto mr-auto" style="max-width: 80rem;">
    <div class="card-header">{{ resource.title }}</div>
    <div class="card-body col-md-4 m-auto col">
      <p class="card-title">{{ resource.description }}</p>
      <a href="{{ resource.link }}" class="card-text">Go to Resource</a></br>
      {% if current_user.is_authenticated %}
      <a href="/resources/delete/{{ resource.id }}"><small>Delete Resource</small></a>
      {% endif %}
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

tutorial_app/templates/signin.html
<!-- signup.html -->
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 m-auto text-center">
  <h1>Sign In</h1>

  <form action="{{ url_for('auth.signin') }}" method="POST" class="m-auto text-center col-md-6">
    {{ form.csrf_token }}
    <fieldset>
      <legend>Enter your credentials</legend>
      <div class="form-group col">
        <div class="col-sm-10">
          {{ form.username.label }}
          {{ form.username }}
        </div>
      </div>
      <ul>
        {% for error in form.username.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      <div class="form-group col">
        <div class="col-sm-10">
          {{ form.password.label }}
          {{ form.password }}
        </div>
      </div>
      <ul>
        {% for error in form.password.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>

      {{ form.submit }}
    </fieldset>
  </form>
</div>

{% endblock %}

tutorial_app/templates/signup.html
<!-- signup.html -->
{% extends 'base.html' %}
{% block content %}

<div class="col-md-6 m-auto text-center">
  <h1>Sign Up</h1>

  <form action="{{ url_for('auth.signup') }}" method="POST" class="m-auto text-center col-md-6">
    {{ form.csrf_token }}
    <fieldset>
      <legend>Enter your credentials</legend>
      <div class="form-group col">
        <div class="col-sm-10">
          {{ form.username.label }}
          {{ form.username }}
        </div>
      </div>
      <ul>
        {% for error in form.username.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      <div class="form-group col">
        <div class="col-sm-10">
          {{ form.password.label }}
          {{ form.password }}
        </div>
      </div>
      <ul>
        {% for error in form.password.errors %}
        <li class="error">{{ error }}</li>
        {% endfor %}
      </ul>
      {{ form.submit }}
    </fieldset>
  </form>
</div>
{% endblock %}

tutorial_app/templates/tutorial_detail.html
{% extends 'base.html' %}
{% block content %}

<h5 class="ml-auto mr-auto mt-5 text-center">Your progress:</h5>

<div class="progress ml-auto mr-auto mb-5" style="width: 33%;">
  <div class="progress-bar bg-success" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
</div>

<div class="m-auto text-center col-md-9">
  <h1>{{ tutorial.title }}</h1>
  <small>{{ tutorial.difficulty }}</small>

  <p>{{ tutorial.body }}</p>
</div>

{% if current_user.is_authenticated %}

  <div class="m-auto text-center col-md-4">
    <small>Have edits in mind?</small>

    <a href="/tutorials/edit/{{ tutorial.id }}">Edit Tutorial</a></br>
    <a href="/tutorials/delete/{{ tutorial.id }}"><small>Delete Tutorial</small></a>
  </div>

{% endif %}

{% endblock %}